#!/usr/bin/env bash
source ./common

[ -d "${DEV_HOME}" ] || mkdir -p "${DEV_HOME}"

# Set Bash as default shell
if [[ "/bin/bash" != "$(dscl . -read ~/ UserShell | sed 's/UserShell: //')" ]]; then
    chsh -s /bin/bash
fi

# bootstrap homebrew
exists-in-path brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install homebrew deps
brew update
brew bundle --file="${REPO_PATH}/brew/Brewfile"

# setup environment links
symlink-src-to-target "${REPO_PATH}/bash_profile" "${HOME}/.bash_profile"
symlink-src-to-target "${REPO_PATH}/profile.sh" "${HOME}/.profile"
symlink-src-to-target "${REPO_PATH}/gitconfig" "${HOME}/.gitconfig"
symlink-src-to-target "${REPO_PATH}/gitignore" "${HOME}/.gitignore"
