#!/usr/bin/env bash
source ./common

[ -d "${DEV_HOME}" ] || mkdir -p "${DEV_HOME}"

sudo xcodebuild -license accept
xcode-select --install;

# bootstrap homebrew
exists-in-path brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install homebrew deps
brew update
brew bundle --file="${REPO_PATH}/brew/Brewfile"

